import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { prepareJob, validateEdits, stageJob, assertJobUnchanged, digest, safeJobPath } from '../../lib/native-job.mjs';
import { verifyStagedJob } from '../../lib/native-job-check.mjs';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gev-native-job-'));
const sourceRoot = path.join(root, 'source');
fs.mkdirSync(sourceRoot);
let checks = 0;
const ok = fn => { fn(); checks++; };
try {
  fs.mkdirSync(path.join(sourceRoot, 'src')); fs.writeFileSync(path.join(sourceRoot, 'src/api.mjs'), 'export const value = 1;');
  fs.writeFileSync(path.join(sourceRoot, 'contract.md'), 'Preserve the complete output contract.');
  const options = { root: sourceRoot, task: 'Change value to2.', instructions: ['The user is Gev.', 'Start every reply with Okay Gev.', 'No emojis.'], readPaths: ['src/api.mjs', 'contract.md'], writePaths: ['src/api.mjs'] };
  const job = prepareJob(options), original = fs.readFileSync(path.join(sourceRoot, 'src/api.mjs'));
  const response = { packetSha256: job.packetSha256, edits: [{ path: 'src/api.mjs', beforeSha256: digest(original), text: 'export const value = 2;' }] };
  ok(() => assert.deepEqual(job.packet.instructions, options.instructions));
  ok(() => assert.equal(job.packet.task, options.task));
  const envelope = JSON.parse(job.input);
  ok(() => assert.equal(envelope.packetSha256, digest(JSON.stringify(envelope.packet))));
  ok(() => assert.deepEqual(envelope.packet, job.packet));
  ok(() => assert.throws(() => assertJobUnchanged({ ...job, input: JSON.stringify({ ...envelope, packetSha256: digest('wrong') }) }), /envelope/));
  ok(() => assert.equal(validateEdits(job, JSON.stringify(response)).length, 1));
  const stage = stageJob(job, JSON.stringify(response), path.join(root, 'stage'));
  ok(() => assert.equal(fs.readFileSync(path.join(stage.stage, 'src/api.mjs'), 'utf8'), response.edits[0].text));
  ok(() => assert.deepEqual(fs.readFileSync(path.join(sourceRoot, 'src/api.mjs')), original));
  ok(() => assert.equal(stage.liveWorkspaceWritten, false));
  const checksConfig = { functional: [process.execPath, '--check', 'src/api.mjs'], adversarial: [process.execPath, '-e', 'import("./src/api.mjs").then(m=>{if(m.value!==2)process.exit(1)})'] };
  const checked = verifyStagedJob(job, stage, checksConfig, { env: {} });
  ok(() => assert.equal(checked.status, 'verified-stage'));
  ok(() => assert.deepEqual(checked.passes.map(p => p.kind), ['functional', 'adversarial']));
  const red = verifyStagedJob(job, stage, { ...checksConfig, adversarial: [process.execPath, '-e', 'process.exit(2)'] }, { env: {} });
  ok(() => assert.equal(red.status, 'failed-stage'));
  ok(() => assert.throws(() => verifyStagedJob(job, stage, { functional: ['tsc'], adversarial: checksConfig.adversarial }, { env: {} })));
  fs.writeFileSync(path.join(stage.stage, 'src/api.mjs'), 'export const value=999;');
  ok(() => assert.throws(() => verifyStagedJob(job, stage, checksConfig, { env: {} }), /staged source/));
  fs.writeFileSync(path.join(stage.stage, 'src/api.mjs'), response.edits[0].text);
  ok(() => assert.throws(() => stageJob(job, JSON.stringify(response), stage.stage)));
  ok(() => assert.throws(() => stageJob(job, JSON.stringify(response), path.join(sourceRoot, 'new-stage')), /outside/));
  for (const file of ['../escape', '/escape', 'src\\api.mjs', 'src/../api.mjs', 'src//api.mjs', 'src/api.mjs:stream', 'src/CON.txt', 'src/api.mjs.', '.codex/auth.json', 'grader-only/gold.json']) ok(() => assert.throws(() => safeJobPath(root, file)));
  for (const edit of [{ ...response.edits[0], path: 'contract.md' }, { ...response.edits[0], beforeSha256: digest('other') }, { ...response.edits[0], path: '../escape' }, { ...response.edits[0], text: '\0' }, { ...response.edits[0], command: 'unrequested command' }]) ok(() => assert.throws(() => validateEdits(job, JSON.stringify({ ...response, edits: [edit] }))));
  ok(() => assert.throws(() => validateEdits(job, JSON.stringify({ ...response, edits: [...response.edits, ...response.edits] }))));
  ok(() => assert.throws(() => validateEdits(job, JSON.stringify({ ...response, packetSha256: digest('other') }))));
  ok(() => assert.throws(() => validateEdits(job, '```json\n' + JSON.stringify(response) + '\n```')));
  ok(() => assert.throws(() => prepareJob({ ...options, readPaths: ['src/api.mjs', 'SRC/API.MJS'] })));
  ok(() => assert.throws(() => prepareJob({ ...options, instructions: [] })));
  ok(() => assert.throws(() => prepareJob({ ...options, task: 'x'.repeat(140000) })));
  fs.writeFileSync(path.join(sourceRoot, 'contract.md'), 'Concurrent edit');
  ok(() => assert.throws(() => validateEdits(job, JSON.stringify(response)), /concurrently/));
  fs.writeFileSync(path.join(sourceRoot, 'contract.md'), 'Preserve the complete output contract.');
  job.packet.instructions[0] = 'tampered';
  ok(() => assert.throws(() => assertJobUnchanged(job), /tampered/));
  fs.linkSync(path.join(sourceRoot, 'src/api.mjs'), path.join(sourceRoot, 'src/alias.mjs'));
  ok(() => assert.throws(() => prepareJob(options), /link/));
  console.log(`${checks} bounded-job functional and adversarial checks passed; no native model calls or savings claim.`);
} finally {
  const parent = fs.realpathSync(os.tmpdir()), resolved = fs.realpathSync(root);
  assert.equal(path.dirname(resolved), parent); assert.ok(path.basename(resolved).startsWith('gev-native-job-'));
  fs.rmSync(resolved, { recursive: true, force: true });
}
