import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {usageOf,flowOf,jobsOf,contained,validateResume,limitsOf,profileEnv,taskContextReceived,skillIsolation,skillConfigPaths,contextTransport,inputReceived,assertFreshAllowance} from './run.mjs';import {loadTaskList} from '../ccstudy/run.mjs';
import {summarize} from './summary.mjs';
import {spawnSync} from 'node:child_process';
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++;};
const count=(total,last)=>({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:total,last_token_usage:{input_tokens:last}}}});
eq(usageOf([]).promptRaw,null);
const call=(name,args,id)=>({type:'response_item',payload:{type:'function_call',name,arguments:args,call_id:id}});
eq(flowOf([]),{outerToolCalls:0,waitCalls:0,shortWaitCalls:0,minRequestedWaitMs:null});
const pending=call('functions.wait','{"yield_time_ms":1000}','poll');
eq(flowOf([pending,pending,call('wait','{"yield_time_ms":30000}','later'),call('exec','{}','read')]),{outerToolCalls:3,waitCalls:2,shortWaitCalls:1,minRequestedWaitMs:1000});
eq(flowOf([call('wait','bad','x'),call('wait','{"yield_time_ms":"1000"}','y'),call('wait','{"yield_time_ms":-1}','z')]),{outerToolCalls:3,waitCalls:3,shortWaitCalls:0,minRequestedWaitMs:null});
const u={input_tokens:123,cached_input_tokens:100,output_tokens:9};
eq(usageOf([count(u,30),count(u,30)]),{promptRaw:123,cachedInput:100,output:9,contextPeak:30,contextMean:30,tokenSamples:1});
eq(usageOf([count({...u,input_tokens:50},20),count(u,40)]).contextMean,30);
const jobs=jobsOf([{id:'a'},{id:'b'}],3);eq(jobs.length,12);eq(jobs.slice(0,2).map(x=>x.arm),['plain','plugin']);eq(jobs.slice(4,6).map(x=>x.arm),['plugin','plain']);
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gev-study-test-'));
const plan={sha:'x',plugin:'atlias',model:'x',effort:'medium',lean:false,tasks:[{id:'a',sha256:'old'}]};
eq(contextTransport(plan),'native-hook');eq(contextTransport({contextTransport:'caller-v1'}),'caller-v1');
assert.throws(()=>contextTransport({contextTransport:'unknown'}),/unknown/);n++;
validateResume(plan,{...plan,contextTransport:'native-hook'});n++;
assert.throws(()=>validateResume(plan,{...plan,contextTransport:'caller-v1'}),/transport/);n++;
const callerPlan={...plan,contextTransport:'caller-v1',driverSha256:'first'};
validateResume(callerPlan,{...callerPlan});n++;
assert.throws(()=>validateResume(callerPlan,{...callerPlan,driverSha256:'changed'}),/driver/);n++;
const message=(role,text)=>({type:'response_item',payload:{type:'message',role,content:[{type:'input_text',text}]}});
const fullInput='Task\r\n雪\n\n[atlias task context]\nExact file data';
eq(inputReceived([message('user',fullInput)],fullInput),true);
eq(inputReceived([message('assistant',fullInput)],fullInput),false);
eq(inputReceived([message('developer',fullInput)],fullInput),false);
eq(inputReceived([message('user',fullInput.slice(0,-1))],fullInput),false);
eq(inputReceived([message('user',fullInput)],''),false);
const fresh={snapshotFetchedAt:100000,windows:[{percentUsed:10}],codexCredits:{enabled:false}};
assertFreshAllowance(fresh,100000);n++;
for(const changed of [{snapshotFetchedAt:0},{snapshotFetchedAt:106000},{windows:[]},{windows:[{percentUsed:-1}]},{windows:[{percentUsed:101}]},{windows:[{percentUsed:null}]},{codexCredits:{enabled:true}},{codexCredits:undefined}]){assert.throws(()=>assertFreshAllowance({...fresh,...changed},100000),/no model call/);n++;}
eq(skillIsolation(null),'file-path-v1');eq(skillIsolation(plan),'directory-path-legacy');
validateResume(plan,{...plan,skillsIsolation:'directory-path-legacy'});n++;
assert.throws(()=>validateResume(plan,{...plan,skillsIsolation:'file-path-v1'}),/skill isolation/);n++;
assert.throws(()=>skillIsolation({skillsIsolation:'unknown'}),/unknown/);n++;
eq(profileEnv(true),{ATLIAS_FLAG_LEAN_BRIEF:'1',ATLIAS_FLAG_GATE_RUNS_CHECK:'1'});
eq(profileEnv(false),{});
eq(profileEnv(false,true),{ATLIAS_FLAG_TASK_CONTEXT:'1'});
eq(taskContextReceived([{type:'response_item',payload:{type:'message',role:'developer',content:[{text:'[atlias task context] source'}]}}]),true);
eq(taskContextReceived([{type:'response_item',payload:{type:'message',role:'assistant',content:[{text:'[atlias task context] source'}]}}]),false);
eq(taskContextReceived([call('exec','[atlias task context]','fake')]),false);
eq(profileEnv(true,true),{ATLIAS_FLAG_LEAN_BRIEF:'1',ATLIAS_FLAG_GATE_RUNS_CHECK:'1',ATLIAS_FLAG_TASK_CONTEXT:'1'});
assert.throws(()=>validateResume(plan,{...plan,taskContext:true}),/flags/);n++;
eq(limitsOf([]),{stopPercent:60,timeoutMin:12});
for(const args of [['--stop-percent','NaN'],['--stop-percent','101'],['--timeout-min','Infinity'],['--timeout-min','0']]){assert.throws(()=>limitsOf(args),/finite/);n++;}
validateResume(plan,{...plan,repeats:3});n++;
validateResume({...plan,repeats:2},{...plan,repeats:2});n++;
validateResume({...plan,repeats:2},{...plan,repeats:3});n++;
assert.throws(()=>validateResume({...plan,repeats:2},{...plan,repeats:1}),/decrease repeats/);n++;
assert.throws(()=>validateResume(plan,{...plan,tasks:[{id:'a',sha256:'new'}]}),/task hashes/);n++;
const row=(task,arm,promptRaw,solved=true)=>({task,family:task,arm,promptRaw,solved,valid:true,exitCode:0,repeat:1});
const report=summarize([row('a','plain',10),row('a','atlias',20,false),row('b','plain',30),row('b','atlias',40),row('unmatched','atlias',500)]);
eq(report.comparisons[0].pairedStats.atlias,{n:2,solved:1,promptRaw:60,perSolved:60,contextPeak:0});
eq(report.comparisons[0].pairedStats.plain.perSolved,20);
eq(report.comparisons[0].rawRatio.bootLo,null);
eq(summarize([row('a','plain',null)]).excluded.length,1);
eq(summarize([row('a','plain',-1)]).excluded.length,1);
eq(summarize([{...row('a','plain',1),valid:false,invalidReason:'ambiguous contract'}]).excluded[0].reason,'ambiguous contract');
assert.throws(()=>summarize([row('a','plain',1),row('a','plain',1)]),/duplicate/);n++;
eq(summarize([row('a','plain',10),{...row('a','atlias',20),timedOut:true}]).comparisons.length,0);
eq(summarize([row('a','plain',10),row('a','atlias',20),{...row('a','plain',10),repeat:2},{...row('a','atlias',20),repeat:2}]).comparisons[0].semanticFamilies,1);
try{
  const skillDir=path.join(root,'skill');fs.mkdirSync(skillDir);fs.writeFileSync(path.join(skillDir,'SKILL.md'),'# Fixture');
  eq(skillConfigPaths([skillDir],'directory-path-legacy'),[skillDir]);
  eq(skillConfigPaths([skillDir],'file-path-v1').every(p=>fs.statSync(p).isFile()),true);
  const envCheck=spawnSync(process.execPath,['--input-type=module','-e',`import {config} from ${JSON.stringify(new URL('../../lib/core.mjs',import.meta.url).href)};console.log(JSON.stringify(config().flags));`],{encoding:'utf8',env:{...process.env,ATLIAS_HOME:path.join(root,'state'),...profileEnv(true,true)}});
  assert.equal(envCheck.status,0);const actualFlags=JSON.parse(envCheck.stdout);eq([actualFlags.leanBrief,actualFlags.gateRunsCheck,actualFlags.taskContext],[true,true,true]);
  assert.throws(()=>contained(root,'../outside'));n++;assert.throws(()=>contained(root,root));n++;
  fs.writeFileSync(path.join(root,'task.json'),JSON.stringify({id:'x'}));fs.writeFileSync(path.join(root,'list.json'),JSON.stringify({tasks:[{id:'x',file:'task.json',sha256:'changed'}]}));assert.throws(()=>loadTaskList(path.join(root,'list.json'),root),/hash/);n++;
}finally{fs.rmSync(root,{recursive:true,force:true});}
console.log(`${n} native benchmark protocol checks passed; no model calls.`);
