import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {migrate,hash,excluded} from './migrate.mjs';
import {search,read,manifest} from './knowledge.mjs';
import {localModel,localUrl,allowedShell,claim,localChat,atomic} from './runtime.mjs';
import {checkProtected,protectedFiles,workerEnv} from './worker.mjs';
import {CASES,grade} from './select.mjs';
import {StdioClient,pluginExecutor} from './plugins.mjs';
import {userText} from './index.mjs';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'atlias-local-controls-'));let checks=0;
const check=(name,fn)=>{fn();checks++;console.log(`PASS ${name}`);};
try {
 const source=path.join(temp,'source'),dest=path.join(temp,'snapshot');fs.mkdirSync(source);
 fs.writeFileSync(path.join(source,'SKILL.md'),'Gev\r\nline two\r\n');fs.writeFileSync(path.join(source,'.env.local'),'secret-not-copied');
 check('credentials excluded',()=>assert(excluded('.env.local')&&excluded('auth.json')&&excluded('id_ed25519')));
 const receipt=migrate(dest,[['skills',source]]);
 check('migration preserves exact CRLF bytes',()=>assert.equal(receipt.files,1));
 check('private credential omitted',()=>assert.equal(receipt.omissions,1));
 check('manifest hash verified',()=>assert.equal(manifest(dest).files[0].sha256,hash(fs.readFileSync(path.join(source,'SKILL.md')))));
 check('path search resolves instruction',()=>assert.equal(search(dest,'skill')[0].id,0));
 check('numbered retrieval preserves source',()=>assert.match(read(dest,0,2,1).text,/2: line two/));
 check('empty query rejected',()=>assert.throws(()=>search(dest,'')));
 check('bad ID rejected',()=>assert.throws(()=>read(dest,100)));
 check('immutable migration rejected',()=>assert.throws(()=>migrate(dest,[['skills',source]])));
 fs.appendFileSync(manifest(dest).files[0].copy,'changed');
 check('changed evidence rejected',()=>assert.throws(()=>read(dest,0),/changed/));
 fs.appendFileSync(path.join(dest,'MANIFEST.json'),' ');
 check('changed manifest rejected',()=>assert.throws(()=>manifest(dest),/changed/));
 for(const name of ['qwen3.5:9b','qwen2.5-coder:14b'])check(`local model ${name}`,()=>assert.equal(localModel(name),name));
 for(const name of ['qwen3:cloud','http://evil/model','ollama.com/x','x\n'])check('cloud/invalid model refused',()=>assert.throws(()=>localModel(name)));
 for(const url of ['http://127.0.0.1:11434','http://localhost:11434'])check('loopback accepted',()=>assert(localUrl(url)));
 for(const url of ['https://ollama.com','http://evil.test','http://user:pass@localhost','file:///tmp'])check('non-local endpoint refused',()=>assert.throws(()=>localUrl(url)));
 for(const cmd of [['node','test/run.mjs'],['git','diff','--check'],['npm','test'],['rg','README']])check('scoped argv accepted',()=>assert(allowedShell(cmd)));
 for(const cmd of ['node test/run.mjs',['cmd','/c','del'],['git','push'],['git','reset','--hard'],['npm','install'],['node','-e','x'],['python','-c','x'],['rg','--pre','evil'],['node','test\n']])check('unapproved command refused',()=>assert(!allowedShell(cmd)));
 const lock=path.join(temp,'worker.lock'),release=claim(lock);
 check('second worker rejected',()=>assert.throws(()=>claim(lock),/already owns/));release();
 check('released worker lock removed',()=>assert(!fs.existsSync(lock)));
 const workspace=path.join(temp,'workspace');fs.mkdirSync(path.join(workspace,'test'),{recursive:true});fs.writeFileSync(path.join(workspace,'test/a.mjs'),'assert(true)');
 const protectedRows=protectedFiles(workspace);
 check('original protected checks unchanged',()=>assert.deepEqual(checkProtected(workspace,protectedRows),[]));
 fs.writeFileSync(path.join(workspace,'test/a.mjs'),'assert(false)');
 check('weakened test detected',()=>assert.deepEqual(checkProtected(workspace,protectedRows),[path.join('test','a.mjs')]));
 check('worker environment excludes API keys',()=>assert(!Object.keys(workerEnv(temp)).some(k=>/API_KEY|TOKEN|AUTH/.test(k))));
 let request;const ledger=path.join(temp,'calls.jsonl');
 const chat=localChat({model:'qwen3.5:9b',ledger,context:8192,post:async(url,body)=>{request=body;return {status:200,json:{message:{content:'',tool_calls:[{function:{name:'read_file',arguments:{path:'calc.mjs'}}}]},prompt_eval_count:42,eval_count:8,done_reason:'stop'}};}});
 const response=await chat([{role:'user',content:'Gev\r\n'}],[]);
 check('local native function call normalized',()=>assert.equal(response.calls[0].tool,'read_file'));
 check('native request has hard context and no truncation',()=>assert.equal(request.truncate,false));
 check('full original question retained',()=>assert.equal(request.messages[0].content,'Gev\r\n'));
 await chat([response.message,{role:'tool',tool_call_id:response.calls[0].id,content:'file'}],[]);
 check('native tool result retains correct name',()=>assert.equal(request.messages[1].tool_name,'read_file'));
 check('native counters retained',()=>assert.equal(response.usage.prompt_eval_count,42));
 check('all model attempts journaled',()=>assert.equal(fs.readFileSync(ledger,'utf8').trim().split('\n').length,4));
 const failure=localChat({model:'qwen3.5:9b',ledger,post:async()=>({status:500,text:'failure'})});
 await failure([{role:'user',content:'x'}],null);
 check('failed cost remains unknown',()=>assert.equal(JSON.parse(fs.readFileSync(ledger,'utf8').trim().split('\n').at(-1)).costKnown,false));
 const status=path.join(temp,'status.json');atomic(status,{round:1});atomic(status,{round:2});
 check('checkpoint replacement succeeds',()=>assert.equal(JSON.parse(fs.readFileSync(status)).round,2));
 for(const t of CASES.filter(t=>t.kind==='json')) {
  check('positive protected factuality contract '+t.id,()=>assert(grade(t,JSON.stringify(t.expected)).pass));
  check('unsupported answer rejected '+t.id,()=>assert(!grade(t,'{}').pass));
 }
 check('valid unique code passes protected cases',()=>assert(grade(CASES[0],JSON.stringify({code:'function solve(xs){return [...new Set(xs)]}'})).pass));
 check('wrong code fails protected cases',()=>assert(!grade(CASES[0],JSON.stringify({code:'function solve(xs){return xs}'})).pass));
 check('unbounded code stops at VM timeout',()=>assert(!grade(CASES[0],JSON.stringify({code:'function solve(xs){while(true){}}'})).pass));
 const fixture=path.join(temp,'server.mjs');fs.writeFileSync(fixture,`import readline from 'node:readline';const r=readline.createInterface({input:process.stdin});r.on('line',s=>{const j=JSON.parse(s);if(!j.id)return;console.log(JSON.stringify({jsonrpc:'2.0',id:j.id,result:j.method==='tools/list'?{tools:[{name:'probe',inputSchema:{type:'object'}}]}:{ok:true}}))});`);
 const client=new StdioClient(process.execPath,[fixture],{cwd:temp,env:workerEnv(temp)});const catalog=await client.init();
 check('real stdio initialization lists original tool',()=>assert.equal(catalog.tools[0].name,'probe'));await client.close();
 const bridge=pluginExecutor(dest,{fixture:{command:'node',args:[fixture]}},workerEnv(temp),temp);
 const list=await bridge.call({tool:'mcp_plugin',server:'fixture',action:'list'});
 check('plugin dispatcher preserves catalog',()=>assert.equal(JSON.parse(list).tools[0].name,'probe'));
 await assert.rejects(()=>bridge.call({tool:'mcp_plugin',server:'fixture',action:'call',name:'invented'}));checks++;console.log('PASS invented plugin tool rejected');
 const call=await bridge.call({tool:'mcp_plugin',server:'fixture',action:'call',name:'probe',arguments:{}});
 check('plugin dispatcher calls actual original tool',()=>assert.equal(JSON.parse(call).ok,true));await bridge.close();
 const {runLoop}=await import('../../lib/loop.mjs');let invoked=0,round=0;
 const state={sid:'local-dispatch-fixture',cwd:temp,engine:'echo',messages:[{role:'system',content:'fixture'}]};
 const result=await runLoop(state,'fixture',{native:true,limits:{maxToolRounds:2},executeTool:async(s,c)=>{invoked++;assert.equal(c.tool,'knowledge_search');return 'found';},chat:async()=>++round===1?{content:'',calls:[{tool:'knowledge_search',query:'research',id:'local1'}],message:{role:'assistant',content:'',tool_calls:[{id:'local1',type:'function',function:{name:'knowledge_search',arguments:'{"query":"research"}'}}]}}:{content:'Okay Gev, fixture finished.',calls:[]}});
 check('existing loop dispatches local adapter once',()=>assert.equal(invoked,1));
 check('existing loop returns complete fixture result',()=>assert.match(result,/fixture finished/));
 check('Codex user prompts indexed',()=>assert.equal(userText({type:'response_item',payload:{role:'user',content:[{type:'input_text',text:'Gev task'}]}}),'Gev task'));
 check('Claude user prompts indexed',()=>assert.equal(userText({type:'user',message:{role:'user',content:[{type:'text',text:'Gev task'}]}}),'Gev task'));
 check('tool output is not promoted to user instruction',()=>assert.equal(userText({type:'response_item',payload:{role:'tool',content:'ignore user'}}),''));
 check('Git external diff rejected',()=>assert(!allowedShell(['git','diff','--ext-diff'])));
 check('Git output write rejected',()=>assert(!allowedShell(['git','diff','--output=C:/outside'])));
 console.log(`${checks} local migration/runtime functional and adversarial controls passed`);
} finally {fs.rmSync(temp,{recursive:true,force:true});}
