import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { DATASET,hash,PUBLISHER_CARD_SHA256 } from './protocol.mjs';
import { loadNativePlan,main } from './native-run.mjs';
import { normalizeAnswer,responseFrom,toolCallsFrom,nativeSession } from './native-session.mjs';
import { nativeReport } from './native-report.mjs';
let checks=0;const ok=fn=>{fn();checks++;};
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gev-aa-native-'));
try{
  const prepared=path.join(root,'prepared');fs.mkdirSync(prepared);
  const questions=Array.from({length:600},(_,i)=>({id:'fixture-'+i,questionSha256:hash('q'+i),prompt:'Question fixture '+i}));
  const original={benchmark:'AA-Omniscience-Public',dataset:DATASET,questionManifestSha256:hash(JSON.stringify(questions))};
  fs.writeFileSync(path.join(prepared,'questions.json'),JSON.stringify(questions));fs.writeFileSync(path.join(prepared,'plan.json'),JSON.stringify(original));
  const options={prepared,host:'codex',arm:'plain',model:'pinned-fixture',effort:'medium',native:process.execPath,sourceSha:hash('source')};
  const plain=loadNativePlan(options),atlias=loadNativePlan({...options,arm:'atlias'});
  ok(()=>assert.equal(plain.jobs.length,600));ok(()=>assert.equal(atlias.jobs.length,600));
  ok(()=>assert.deepEqual(plain.jobs.map(j=>j.prompt),atlias.jobs.map(j=>j.prompt)));
  ok(()=>assert.notEqual(plain.system,atlias.system));
  ok(()=>assert.equal(plain.plan.paidCredits,false));ok(()=>assert.equal(plain.plan.automaticRetries,false));
  const flags=['--prepared',prepared,'--host','codex','--arm','plain','--model','fixture','--effort','medium','--native',process.execPath,'--run'];
  const noCsv=path.join(root,'no-csv');
  await assert.rejects(main([...flags,'--out',noCsv]),/pinned --dataset/);checks++;
  ok(()=>assert.equal(fs.existsSync(path.join(noCsv,'attempts')),false));
  const corruptCsv=path.join(root,'bad.csv');fs.writeFileSync(corruptCsv,'not the pinned data');
  const badCsvOut=path.join(root,'corrupt-csv');
  await assert.rejects(main([...flags,'--out',badCsvOut,'--dataset',corruptCsv]),/pinned revision/);checks++;
  ok(()=>assert.equal(fs.existsSync(path.join(badCsvOut,'attempts')),false));
  ok(()=>assert.equal(normalizeAnswer('Okay Gev\nAnswer'),'Answer'));
  ok(()=>assert.equal(normalizeAnswer('Okay Gev: I do not know.'),'I do not know.'));
  ok(()=>assert.equal(normalizeAnswer('Okay Gev'),''));
  ok(()=>assert.equal(normalizeAnswer('Okay Gev\n.NET'),'.NET'));
  ok(()=>assert.throws(()=>normalizeAnswer('Okay Gevish'),/canary/));
  ok(()=>assert.throws(()=>normalizeAnswer('Invented answer'),/canary/));
  ok(()=>assert.equal(responseFrom('codex',[{type:'item.completed',item:{type:'agent_message',text:'last'}}]),'last'));
  ok(()=>assert.equal(responseFrom('claude',[{type:'result',result:'answer'}]),'answer'));
  ok(()=>assert.equal(toolCallsFrom('codex',[{type:'item.completed',item:{type:'command_execution'}}]),1));
  ok(()=>assert.equal(toolCallsFrom('claude',[{type:'assistant',message:{content:[{type:'tool_use'},{type:'tool_use'}]}}]),2));
  ok(()=>assert.equal(toolCallsFrom('codex',[{type:'item.completed',item:{type:'agent_message'}}]),0));
  fs.writeFileSync(path.join(prepared,'questions.json'),JSON.stringify(questions.slice(1)));
  ok(()=>assert.throws(()=>loadNativePlan(options),/manifest/));
  fs.writeFileSync(path.join(prepared,'questions.json'),JSON.stringify(questions));
  ok(()=>assert.throws(()=>loadNativePlan({...options,host:'unsupported'}),/pin/));
  const protectedDir=path.join(root,'protected');fs.mkdirSync(protectedDir);
  const prompts=[{identity:'claude:atlias:question-id',host:'claude',arm:'atlias',id:'question-id',questionSha256:hash('q'),responseSha256:hash('candidate'),prompt:'Protected semantic template with fixture gold.',promptSha256:hash('Protected semantic template with fixture gold.')}];
  fs.writeFileSync(path.join(protectedDir,'judge-prompts.json'),JSON.stringify(prompts));
  fs.writeFileSync(path.join(protectedDir,'plan.json'),JSON.stringify({benchmark:original.benchmark,dataset:DATASET,judgePromptsSha256:hash(JSON.stringify(prompts)),publisherCardSha256:PUBLISHER_CARD_SHA256,templateSha256:hash('template'),responseLedgerSha256:hash('responses')}));
  const judge=loadNativePlan({...options,prepared:protectedDir,judge:true,solverHost:'claude',solverArm:'atlias'});
  ok(()=>assert.equal(judge.jobs.length,1));ok(()=>assert.equal(judge.jobs[0].questionId,'question-id'));
  ok(()=>assert.equal(judge.plan.host,'codex'));ok(()=>assert.equal(judge.plan.solverHost,'claude'));
  ok(()=>assert.equal(judge.plan.plannedQuestions,600));
  const response={id:questions[0].id,questionSha256:questions[0].questionSha256,host:'codex',arm:'plain',response:'fixture',responseSha256:hash('fixture'),valid:true,planSha256:hash(JSON.stringify(plain.plan)),usage:{promptRaw:10,cachedInput:0,output:3}};
  const judgePlan={...judge.plan,solverHost:'codex',solverArm:'plain'};
  const grade={...response,judge:judgePlan.model,label:'CORRECT',planSha256:hash(JSON.stringify(judgePlan)),usage:{promptRaw:20,cachedInput:0,output:1}};
  const diagnostic=nativeReport(questions,[response],[grade],{solverPlan:plain.plan,judgePlan});
  ok(()=>assert.equal(diagnostic.complete,false));ok(()=>assert.equal(diagnostic.measuredMetrics,null));
  ok(()=>assert.equal(diagnostic.solverCostIncludingInvalid.rawInput,10));ok(()=>assert.equal(diagnostic.judgeCostIncludingInvalid.rawInput,20));
  const invalid=nativeReport(questions,[{...response,valid:false}],[grade],{solverPlan:plain.plan,judgePlan});
  ok(()=>assert.equal(invalid.graded,0));ok(()=>assert.equal(invalid.solverCostIncludingInvalid.rawInput,10));
  ok(()=>assert.throws(()=>nativeReport(questions,[response,response],[grade],{solverPlan:plain.plan,judgePlan}),/duplicate/));
  ok(()=>assert.throws(()=>nativeReport(questions,[response],[{...grade,responseSha256:hash('other')}],{solverPlan:plain.plan,judgePlan}),/bound/));
  const meter=path.join(root,'meter.mjs');fs.writeFileSync(meter,'console.log(JSON.stringify({windows:[{percentUsed:100}]}))');
  const out=path.join(root,'blocked');
  await assert.rejects(nativeSession({host:'codex',model:'fixture',effort:'medium',native:process.execPath,prompt:'fixture',out,usageCli:meter,authFile:path.join(root,'absent-auth')}),/headroom/);checks++;
  ok(()=>assert.equal(fs.existsSync(out),false));
  fs.writeFileSync(meter,'console.log(JSON.stringify({windows:[{percentUsed:0}]}))');
  const auth=path.join(root,'auth.json');fs.writeFileSync(auth,JSON.stringify({OPENAI_API_KEY:'fake-fixture'}));
  await assert.rejects(nativeSession({host:'codex',model:'fixture',effort:'medium',native:process.execPath,prompt:'fixture',out,usageCli:meter,authFile:auth}),/subscription/);checks++;
  ok(()=>assert.equal(fs.existsSync(out),false));
  fs.writeFileSync(auth,JSON.stringify({tokens:{access_token:'fake-no-real-token'}}));
  const failed=await nativeSession({host:'codex',model:'fixture',effort:'medium',native:process.execPath,prompt:'fixture',out,usageCli:meter,authFile:auth});
  ok(()=>assert.equal(failed.valid,false));ok(()=>assert.equal(failed.authRemoved,true));
  ok(()=>assert.equal(fs.readFileSync(path.join(out,'prompt.txt'),'utf8'),'fixture'));
  await assert.rejects(nativeSession({host:'codex',model:'fixture',effort:'medium',native:process.execPath,prompt:'fixture',out,usageCli:meter,authFile:auth}),/unused/);checks++;
  console.log(`${checks} native factuality preparation/parser/accounting controls passed; zero model calls. Both-host subscription activation and actual semantic scores remain unverified.`);
}finally{
  const resolved=fs.realpathSync(root);assert.equal(path.dirname(resolved),fs.realpathSync(os.tmpdir()));assert.ok(path.basename(resolved).startsWith('gev-aa-native-'));fs.rmSync(resolved,{recursive:true,force:true});
}
