import assert from 'node:assert/strict';
import { parseCsv, metrics, reportGrades, questionPrompt, hash, semanticJudgeTemplate, renderSemanticJudge } from './protocol.mjs';
let checks = 0;
const ok = fn => { fn(); checks++; };
ok(() => assert.deepEqual(parseCsv('\uFEFFa,b\r\n"x,y","a""b"\r\n'), [{ a: 'x,y', b: 'a"b' }]));
ok(() => assert.deepEqual(parseCsv('a,b\n"x\ny",\n'), [{ a: 'x\ny', b: '' }]));
for (const text of ['a,b\n"x,y', 'a,b\n"x"oops,y', 'a,b\nx', 'a,a\nx,y', '']) ok(() => assert.throws(() => parseCsv(text)));
ok(() => assert.deepEqual(metrics([]).hallucinationRate, null));
ok(() => assert.equal(metrics(['CORRECT']).hallucinationRate, null));
ok(() => assert.equal(metrics(['PARTIAL_ANSWER']).omniscienceIndex, 0));
ok(() => assert.equal(metrics(['PARTIAL_ANSWER']).hallucinationRate, 0));
ok(() => assert.equal(metrics(['INCORRECT', 'PARTIAL_ANSWER', 'NOT_ATTEMPTED']).hallucinationRate, 1 / 3));
ok(() => assert.equal(metrics(['CORRECT', 'INCORRECT', 'PARTIAL_ANSWER', 'NOT_ATTEMPTED']).omniscienceIndex, 0));
ok(() => assert.equal(metrics(['NOT_ATTEMPTED']).accuracy, 0));
for (const label of [null, 'A', 'not_attempted', 'UNKNOWN', '__proto__']) ok(() => assert.throws(() => metrics([label])));
const q = [{ id: 'q', questionSha256: hash('question') }], judge = { model: 'scripted-control-not-a-model-result', promptSha256: hash('judge-template') }, grade = { id: 'q', questionSha256: q[0].questionSha256, responseSha256: hash('response'), label: 'CORRECT' };
ok(() => assert.equal(reportGrades(q, [], { judge }).measuredMetrics, null));
ok(() => assert.equal(reportGrades(q, [grade], { judge }).complete, true));
for (const bad of [{ ...grade, id: 'unknown' }, { ...grade, questionSha256: hash('other') }, { ...grade, responseSha256: '' }, { ...grade, label: 'UNKNOWN' }]) ok(() => assert.throws(() => reportGrades(q, [bad], { judge })));
ok(() => assert.throws(() => reportGrades(q, [grade, grade], { judge })));
ok(() => assert.throws(() => reportGrades(q, [grade])));
for (const bad of [{ id: 'q' }, { id: '', questionSha256: hash('question') }, { ...q[0], questionSha256: 'unknown' }]) ok(() => assert.throws(() => reportGrades([bad], [], { judge })));
ok(() => assert.ok(!questionPrompt({ domain: 'domain', subtopic: 'subtopic', question: 'question', answer: 'gold-secret' }).includes('gold-secret')));
ok(() => assert.throws(() => semanticJudgeTemplate('forged easy judge card')));
ok(() => assert.equal(renderSemanticJudge('{question}|{target}|{predicted_answer}', { question: '{target}', target: 'protected-gold', response: '$& {question}' }), '{target}|protected-gold|$& {question}'));
ok(() => assert.throws(() => renderSemanticJudge('{question}', { question: 'q', target: 'gold', response: null })));
console.log(`${checks} AA-Omniscience protocol checks passed; no model calls or benchmark score.`);
